getVectAngle fix - issue #20
jcyrax/pcbmodelgen pull request #21
Opened 2023-05-15 19:48 UTC by ThomHPL

Adding range checks in getVectAngle to fix issue #20.

Zones from a kicad 7.0.0 pcb are ok with this fix.

2023-05-17 21:20 UTC, jcyrax requested changes

2023-05-17 21:20 UTC, jcyrax commented on source/ems_prims.cpp
> +    if ((dot_prod / mag_prod)<=-1.0) {
Please adjust spacing and remove redundant parentheses so that: `if (dot_prod / mag_prod <= -1.0) {`

2023-05-17 21:20 UTC, jcyrax commented on source/ems_prims.cpp
> +    } else if ((dot_prod / mag_prod)>=1.0) {
Please adjust spacing and remove redundant parentheses so that: `} else if (dot_prod / mag_prod >= 1.0) {`

2023-05-17 21:20 UTC, jcyrax commented on source/ems_prims.cpp
> +        angle = acos(dot_prod / mag_prod); // acos(x) returns NaN when input outside of -1 <= x <= 1 which is not guaranteed when using floats
Maybe move comment to previous line so that line length doesn't get to large.

2023-05-17 21:20 UTC, jcyrax commented on .gitignore
> +.vscode
This change should be in different pull request or at least in a separate commit.

2023-05-18 19:09 UTC, merged

2023-05-18 19:10 UTC, jcyrax commented
Thanks for contributing!

2023-05-18 20:12 UTC, ThomHPL commented
You are welcome, a perfected easy way to simulate kicad pcb would be really useful!
FYI, I am working on a branch that adds support for lumped components. It seems to work but I want to make some tests on openEMS to validate the output.